<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Orchid\Platform\Models\Role;

class RolesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $slugs = array(
            "super-yonetici",
            "yonetici",
            "ofis-yoneticisi",
            "ofis-danismani",
            "bireysel-danisman",
            "ofis-asistani"
        );

        $names = array(
            "Süper Yönetici",
            "Yönetici",
            "Ofis Yöneticisi",
            "Ofis Danışmanı",
            "Bireysel Danışman",
            "Ofis Asistanı"
        );

        $permissions = [
            //Super Admin
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 1,
                'platform.systems.roles' => 1,
                'platform.systems.roles.add' => 1,
                'platform.systems.roles.edit' => 1,
                'platform.systems.roles.remove' => 1,
                'platform.systems.users' => 1,
                'platform.systems.users.add' => 1,
                'platform.systems.users.edit' => 1,
                'platform.systems.users.remove' => 1,
                'platform.systems.settings' => 1,
                'platform.systems.provinces' => 1,
                'platform.systems.states' => 1,
                'platform.records' => 1,
                'platform.records.add' => 1,
                'platform.records.edit' => 1,
                'platform.records.remove' => 1,
                'platform.records.detail' => 1,
                'platform.recordtypes' => 1,
                'platform.recordtypes.add' => 1,
                'platform.recordtypes.edit' => 1,
                'platform.recordtypes.remove' => 1,
                'platform.contacts' => 1,
                'platform.contacts.add' => 1,
                'platform.contacts.edit' => 1,
                'platform.contacts.remove' => 1,
                'platform.contacts.detail' => 1,
                'platform.consultants' => 1,
                'platform.consultants.add' => 1,
                'platform.consultants.edit' => 1,
                'platform.consultants.remove' => 1,
                'platform.consultants.detail' => 1,
                'platform.portfolios' => 1,
                'platform.portfolios.add' => 1,
                'platform.portfolios.edit' => 1,
                'platform.portfolios.remove' => 1,
                'platform.portfolios.detail' => 1,
                'platform.offices' => 1,
                'platform.offices.add' => 1,
                'platform.offices.edit' => 1,
                'platform.offices.remove' => 1,
                'platform.myoffice' => 1,
                'platform.calls.add' => 1,
            ],
            //Admin
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 1,
                'platform.systems.roles' => 0,
                'platform.systems.roles.add' => 0,
                'platform.systems.roles.edit' => 0,
                'platform.systems.roles.remove' => 0,
                'platform.systems.users' => 1,
                'platform.systems.users.add' => 1,
                'platform.systems.users.edit' => 1,
                'platform.systems.users.remove' => 1,
                'platform.systems.settings' => 1,
                'platform.systems.provinces' => 0,
                'platform.systems.states' => 0,
                'platform.records' => 1,
                'platform.records.add' => 1,
                'platform.records.edit' => 1,
                'platform.records.remove' => 1,
                'platform.records.detail' => 1,
                'platform.recordtypes' => 1,
                'platform.recordtypes.add' => 1,
                'platform.recordtypes.edit' => 1,
                'platform.recordtypes.remove' => 1,
                'platform.contacts' => 1,
                'platform.contacts.add' => 1,
                'platform.contacts.edit' => 1,
                'platform.contacts.remove' => 1,
                'platform.contacts.detail' => 1,
                'platform.consultants' => 1,
                'platform.consultants.add' => 1,
                'platform.consultants.edit' => 1,
                'platform.consultants.remove' => 1,
                'platform.consultants.detail' => 1,
                'platform.portfolios' => 1,
                'platform.portfolios.add' => 1,
                'platform.portfolios.edit' => 1,
                'platform.portfolios.remove' => 1,
                'platform.portfolios.detail' => 1,
                'platform.offices' => 1,
                'platform.offices.add' => 1,
                'platform.offices.edit' => 1,
                'platform.offices.remove' => 1,
                'platform.myoffice' => 1,
                'platform.calls.add' => 0,
            ],
            //Ofis Yöneticisi
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 1,
                'platform.systems.roles' => 0,
                'platform.systems.roles.add' => 0,
                'platform.systems.roles.edit' => 0,
                'platform.systems.roles.remove' => 0,
                'platform.systems.users' => 0,
                'platform.systems.users.add' => 0,
                'platform.systems.users.edit' => 0,
                'platform.systems.users.remove' => 0,
                'platform.systems.settings' => 0,
                'platform.systems.provinces' => 0,
                'platform.systems.states' => 0,
                'platform.records' => 1,
                'platform.records.add' => 1,
                'platform.records.edit' => 1,
                'platform.records.remove' => 1,
                'platform.records.detail' => 1,
                'platform.recordtypes' => 0,
                'platform.recordtypes.add' => 0,
                'platform.recordtypes.edit' => 0,
                'platform.recordtypes.remove' => 0,
                'platform.contacts' => 1,
                'platform.contacts.add' => 1,
                'platform.contacts.edit' => 1,
                'platform.contacts.remove' => 0,
                'platform.contacts.detail' => 1,
                'platform.consultants' => 1,
                'platform.consultants.add' => 1,
                'platform.consultants.edit' => 1,
                'platform.consultants.remove' => 0,
                'platform.consultants.detail' => 1,
                'platform.portfolios' => 1,
                'platform.portfolios.add' => 1,
                'platform.portfolios.edit' => 1,
                'platform.portfolios.remove' => 1,
                'platform.portfolios.detail' => 1,
                'platform.offices' => 1,
                'platform.offices.add' => 0,
                'platform.offices.edit' => 1,
                'platform.offices.remove' => 0,
                'platform.myoffice' => 1,
                'platform.calls.add' => 0,
            ],
            //Ofis Danışmanı
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 1,
                'platform.systems.roles' => 0,
                'platform.systems.roles.add' => 0,
                'platform.systems.roles.edit' => 0,
                'platform.systems.roles.remove' => 0,
                'platform.systems.users' => 0,
                'platform.systems.users.add' => 0,
                'platform.systems.users.edit' => 0,
                'platform.systems.users.remove' => 0,
                'platform.systems.settings' => 0,
                'platform.systems.provinces' => 0,
                'platform.systems.states' => 0,
                'platform.records' => 1,
                'platform.records.add' => 1,
                'platform.records.edit' => 1,
                'platform.records.remove' => 1,
                'platform.records.detail' => 1,
                'platform.recordtypes' => 0,
                'platform.recordtypes.add' => 0,
                'platform.recordtypes.edit' => 0,
                'platform.recordtypes.remove' => 0,
                'platform.contacts' => 1,
                'platform.contacts.add' => 1,
                'platform.contacts.edit' => 1,
                'platform.contacts.remove' => 0,
                'platform.contacts.detail' => 1,
                'platform.consultants' => 1,
                'platform.consultants.add' => 1,
                'platform.consultants.edit' => 1,
                'platform.consultants.remove' => 0,
                'platform.consultants.detail' => 1,
                'platform.portfolios' => 1,
                'platform.portfolios.add' => 1,
                'platform.portfolios.edit' => 1,
                'platform.portfolios.remove' => 1,
                'platform.portfolios.detail' => 1,
                'platform.offices' => 1,
                'platform.offices.add' => 0,
                'platform.offices.edit' => 0,
                'platform.offices.remove' => 0,
                'platform.myoffice' => 0,
                'platform.calls.add' => 0,
            ],
            //Bireysel Danışman
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 1,
                'platform.systems.roles' => 0,
                'platform.systems.roles.add' => 0,
                'platform.systems.roles.edit' => 0,
                'platform.systems.roles.remove' => 0,
                'platform.systems.users' => 0,
                'platform.systems.users.add' => 0,
                'platform.systems.users.edit' => 0,
                'platform.systems.users.remove' => 0,
                'platform.systems.settings' => 0,
                'platform.systems.provinces' => 0,
                'platform.systems.states' => 0,
                'platform.records' => 1,
                'platform.records.add' => 1,
                'platform.records.edit' => 1,
                'platform.records.remove' => 1,
                'platform.records.detail' => 1,
                'platform.recordtypes' => 0,
                'platform.recordtypes.add' => 0,
                'platform.recordtypes.edit' => 0,
                'platform.recordtypes.remove' => 0,
                'platform.contacts' => 1,
                'platform.contacts.add' => 1,
                'platform.contacts.edit' => 1,
                'platform.contacts.remove' => 0,
                'platform.contacts.detail' => 1,
                'platform.consultants' => 1,
                'platform.consultants.add' => 0,
                'platform.consultants.edit' => 1,
                'platform.consultants.remove' => 0,
                'platform.consultants.detail' => 1,
                'platform.portfolios' => 1,
                'platform.portfolios.add' => 1,
                'platform.portfolios.edit' => 1,
                'platform.portfolios.remove' => 1,
                'platform.portfolios.detail' => 1,
                'platform.offices' => 1,
                'platform.offices.add' => 0,
                'platform.offices.edit' => 0,
                'platform.offices.remove' => 0,
                'platform.myoffice' => 0,
                'platform.calls.add' => 0,
            ],
            //Ofis Asistanı
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 1,
                'platform.systems.roles' => 0,
                'platform.systems.roles.add' => 0,
                'platform.systems.roles.edit' => 0,
                'platform.systems.roles.remove' => 0,
                'platform.systems.users' => 0,
                'platform.systems.users.add' => 0,
                'platform.systems.users.edit' => 0,
                'platform.systems.users.remove' => 0,
                'platform.systems.settings' => 0,
                'platform.systems.provinces' => 0,
                'platform.systems.states' => 0,
                'platform.records' => 0,
                'platform.records.add' => 1,
                'platform.records.edit' => 1,
                'platform.records.remove' => 0,
                'platform.records.detail' => 0,
                'platform.recordtypes' => 0,
                'platform.recordtypes.add' => 0,
                'platform.recordtypes.edit' => 0,
                'platform.recordtypes.remove' => 0,
                'platform.contacts' => 0,
                'platform.contacts.add' => 0,
                'platform.contacts.edit' => 0,
                'platform.contacts.remove' => 0,
                'platform.contacts.detail' => 0,
                'platform.consultants' => 0,
                'platform.consultants.add' => 0,
                'platform.consultants.edit' => 0,
                'platform.consultants.remove' => 0,
                'platform.consultants.detail' => 0,
                'platform.portfolios' => 0,
                'platform.portfolios.add' => 0,
                'platform.portfolios.edit' => 0,
                'platform.portfolios.remove' => 0,
                'platform.portfolios.detail' => 0,
                'platform.offices' => 0,
                'platform.offices.add' => 0,
                'platform.offices.edit' => 0,
                'platform.offices.remove' => 0,
                'platform.myoffice' => 0,
                'platform.calls.add' => 1,
            ],

        ];

        $roles = [];

        for ($i = 0; $i < count($slugs); $i++) {
            array_push($roles, [
                'slug' => $slugs[$i],
                'name' => $names[$i],
                'permissions' => $permissions[$i],
            ]);
        }

        foreach ($roles as $role) {
            Role::create($role);
        }
    }
}
